package gui

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

// iconPNG is the app icon, generated by packaging/icon/gen_icon.py. It is
// embedded so the window, dock and taskbar show it without a separate file.
//
//go:embed icon.png
var iconPNG []byte

// appIcon is iconPNG as a Fyne resource, set on the app and every window.
var appIcon = fyne.NewStaticResource("tlx.png", iconPNG)
